# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - 'README.md'
    - 'azure-pipelines.yml'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Kinny (46ac0732-2092-4bbd-a57f-7a0cd242d2f3)'
        azureContainerRegistry: '{"loginServer":"kinny.azurecr.io", "id" : "/subscriptions/46ac0732-2092-4bbd-a57f-7a0cd242d2f3/resourceGroups/Kinny-linux/providers/Microsoft.ContainerRegistry/registries/kinny"}'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeCommand: up -d
        dockerComposeFileArgs: |
          SEED=$(SEED) 
          HORIZON_ENDPOINT=$(HORIZON_ENDPOINT)
          NETWORK_PASSPHRASE=$(NETWORK_PASSPHRASE)
          APP_ID=$(APP_ID)
          CHANNEL_COUNT=$(CHANNEL_COUNT)
          CHANNEL_STARTING_BALANCE=$(CHANNEL_STARTING_BALANCE)
          CHANNEL_SALT=$(CHANNEL_SALT)
          PORT=$(PORT)
          LOG_LEVEL=$(LOG_LEVEL)
        action: 'Run a Docker Compose command'